project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Affordable Housing Production by Building"
  author:
    - Ashley Noh (cn2671)
    - Jeong Yong Yang (jy3464)
  repo-url: https://github.com/chrisyang922/HousingProduction
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


