# Introduction

Finding affordable housing is a crucial factor when it comes to living in New York City, where the population density is high, real estate prices continue to rise, and income inequality persists. As graduate students living in NYC, we have firsthand experience of the challenges posed by the city’s housing market. We have faced difficulties in finding suitable housing and settling down in this vibrant but expensive city. These experiences have allowed us to appreciate the importance of understanding how affordable housing initiatives shaped the lives of residents and contribute to the city’s socioeconomic dynamic. Access to affordable housing is not only a matter of financial stability but also an important aspect of urban equity as well as a key factor to fostering a community’s well-being. This project allows us to explore this issue through data analysis, leveraging a dataset from the Department of Housing Preservation and Development (HPD). We aim to find trends, disparities, and provide insights in affordable housing development across NYC and hope to contribute to a broader understanding of NYC’s housing landscape and its implications.
